run:
  mode: "csv"                # csv atau database
  watermark_state: "./state/last_run.json"
  output_dir: "./_output"
  report_dir: "./_reports"
  chunk_size: 250000
  timezone: "Asia/Jakarta"

sources:
  csv:
    base_path: "../data_generator/output"
    files:
      products: "products.csv"
      warehouses: "warehouses.csv"
      stock: "stock.csv"
      movements: "stock_movements.csv"
      purchases: "purchase_orders.csv"
      purchase_lines: "purchase_order_details.csv"
      

  database:
    url: "postgresql+psycopg2://admin:admin123@localhost:5433/stock_management"
    tables:
      products: "products"
      warehouses: "warehouses"
      stock: "stock"
      movements: "stock_movements"
      purchases: "purchase_orders"
      purchase_lines: "purchase_order_details"
      

columns_mapping:
  movements:
    timestamp: "movement_date"   # ✅ disesuaikan ke nama kolom di CSV/DB
    quantity: "quantity"
    movement_type: "movement_type"
  stock:
    timestamp: "last_update"
    quantity: "quantity"
  purchases:
    timestamp: "created_at"
  purchase_lines:
    timestamp: "created_at"


business_rules:
  holding_cost_rate_annual: 0.18
  stockout_cost_per_unit: 5.0
  dead_stock_days: 180

metrics:
  resample:
    daily: "D"
    weekly: "W"
    monthly: "MS"

targets:
  export:
    format: ["parquet", "csv"]
    path: "./_analytics_exports"
  database:
    enabled: true
    url: "postgresql+psycopg2://admin:admin123@localhost:5433/stock_management"
    schema: "public"
    materialized_views: true
